// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj8zIPsklVVtydpomAIX9kXo7JVfMkG0g',
    appId: '1:601563030810:web:88c3472bba317f881af8a3',
    messagingSenderId: '601563030810',
    projectId: 'medical-reminder-2cbf7',
    authDomain: 'medical-reminder-2cbf7.firebaseapp.com',
    storageBucket: 'medical-reminder-2cbf7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD190CuTjf1rmNmawvcfRcneS9o_QF6MhI',
    appId: '1:601563030810:android:32acabe76f25f20a1af8a3',
    messagingSenderId: '601563030810',
    projectId: 'medical-reminder-2cbf7',
    storageBucket: 'medical-reminder-2cbf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGvwfhGPR05YVsPyXXzrjazdSQ1jTl6rk',
    appId: '1:601563030810:ios:eab68dd6e20404931af8a3',
    messagingSenderId: '601563030810',
    projectId: 'medical-reminder-2cbf7',
    storageBucket: 'medical-reminder-2cbf7.appspot.com',
    iosBundleId: 'com.example.medicationAdherenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGvwfhGPR05YVsPyXXzrjazdSQ1jTl6rk',
    appId: '1:601563030810:ios:eab68dd6e20404931af8a3',
    messagingSenderId: '601563030810',
    projectId: 'medical-reminder-2cbf7',
    storageBucket: 'medical-reminder-2cbf7.appspot.com',
    iosBundleId: 'com.example.medicationAdherenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj8zIPsklVVtydpomAIX9kXo7JVfMkG0g',
    appId: '1:601563030810:web:89c898ae0e1cb7801af8a3',
    messagingSenderId: '601563030810',
    projectId: 'medical-reminder-2cbf7',
    authDomain: 'medical-reminder-2cbf7.firebaseapp.com',
    storageBucket: 'medical-reminder-2cbf7.appspot.com',
  );
}
